/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
const baseContracts = {
  chainId: 8453,
  deploymentBlock: 39844173,
  StableToken: {
    address: "0x26fac1a59dc80e4b28609fb0da74b3d20e5c8fa4",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  ShakyToken: {
    address: "0xbb55b41a791dcc53aa56673f50de19c9da5ab52c",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  Redemption: {
    address: "0xb9584b11d896ea2c51c5a21a87619963422417f8",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "consideration_",
            type: "address",
          },
          {
            name: "expirationDate_",
            type: "uint256",
          },
          {
            name: "strike_",
            type: "uint256",
          },
          {
            name: "isPut_",
            type: "bool",
          },
        ],
      },
      {
        type: "function",
        name: "STRIKE_DECIMALS",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "_factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "_redeemPair",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "adjustFee",
        inputs: [
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFees",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "collDecimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateral",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralData",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "address_",
                type: "address",
              },
              {
                name: "name",
                type: "string",
              },
              {
                name: "symbol",
                type: "string",
              },
              {
                name: "decimals",
                type: "uint8",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consDecimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consideration",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "considerationData",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "address_",
                type: "address",
              },
              {
                name: "name",
                type: "string",
              },
              {
                name: "symbol",
                type: "string",
              },
              {
                name: "decimals",
                type: "uint8",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
          {
            name: "caller",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "expirationDate",
        outputs: [
          {
            type: "uint40",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fee",
        outputs: [
          {
            type: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fees",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "init",
        inputs: [
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "consideration_",
            type: "address",
          },
          {
            name: "expirationDate_",
            type: "uint40",
          },
          {
            name: "strike_",
            type: "uint256",
          },
          {
            name: "isPut_",
            type: "bool",
          },
          {
            name: "option_",
            type: "address",
          },
          {
            name: "factory_",
            type: "address",
          },
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isPut",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lock",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "locked",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "option",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeemConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeemConsideration",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "strike",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "sweep",
        inputs: [
          {
            name: "holder",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "sweep",
        inputs: [
          {
            name: "holders",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toCollateral",
        inputs: [
          {
            name: "consAmount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unlock",
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "ContractLocked",
      },
      {
        type: "event",
        name: "ContractUnlocked",
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Redeemed",
        inputs: [
          {
            name: "option",
            type: "address",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ArithmeticOverflow",
      },
      {
        type: "error",
        name: "ContractExpired",
      },
      {
        type: "error",
        name: "ContractNotExpired",
      },
      {
        type: "error",
        name: "FeeOnTransferNotSupported",
      },
      {
        type: "error",
        name: "InsufficientBalance",
      },
      {
        type: "error",
        name: "InsufficientCollateral",
      },
      {
        type: "error",
        name: "InsufficientConsideration",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidValue",
      },
      {
        type: "error",
        name: "LockedContract",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "TokenBlocklisted",
      },
    ],
    inheritedFunctions: {},
  },
  Option: {
    address: "0x56755352ffb113547be2f5deaa8f05c2511eb5e4",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
          {
            name: "redemption__",
            type: "address",
          },
        ],
      },
      {
        type: "function",
        name: "adjustFee",
        inputs: [
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balancesOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "collateral",
                type: "uint256",
              },
              {
                name: "consideration",
                type: "uint256",
              },
              {
                name: "option",
                type: "uint256",
              },
              {
                name: "redemption",
                type: "uint256",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFees",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "collateral",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consideration",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "details",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "option",
                type: "address",
              },
              {
                name: "redemption",
                type: "address",
              },
              {
                name: "collateral",
                type: "tuple",
                components: [
                  {
                    name: "address_",
                    type: "address",
                  },
                  {
                    name: "name",
                    type: "string",
                  },
                  {
                    name: "symbol",
                    type: "string",
                  },
                  {
                    name: "decimals",
                    type: "uint8",
                  },
                ],
              },
              {
                name: "consideration",
                type: "tuple",
                components: [
                  {
                    name: "address_",
                    type: "address",
                  },
                  {
                    name: "name",
                    type: "string",
                  },
                  {
                    name: "symbol",
                    type: "string",
                  },
                  {
                    name: "decimals",
                    type: "uint8",
                  },
                ],
              },
              {
                name: "expiration",
                type: "uint256",
              },
              {
                name: "strike",
                type: "uint256",
              },
              {
                name: "isPut",
                type: "bool",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "expirationDate",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fee",
        outputs: [
          {
            type: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "init",
        inputs: [
          {
            name: "redemption_",
            type: "address",
          },
          {
            name: "owner",
            type: "address",
          },
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isPut",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lock",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redemption",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "strike",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
            name: "success",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
            name: "success",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unlock",
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "ContractLocked",
      },
      {
        type: "event",
        name: "ContractUnlocked",
      },
      {
        type: "event",
        name: "Exercise",
        inputs: [
          {
            name: "longOption",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Mint",
        inputs: [
          {
            name: "longOption",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ArithmeticOverflow",
      },
      {
        type: "error",
        name: "ContractExpired",
      },
      {
        type: "error",
        name: "ContractNotExpired",
      },
      {
        type: "error",
        name: "FeeOnTransferNotSupported",
      },
      {
        type: "error",
        name: "InsufficientBalance",
      },
      {
        type: "error",
        name: "InsufficientCollateral",
      },
      {
        type: "error",
        name: "InsufficientConsideration",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidValue",
      },
      {
        type: "error",
        name: "LockedContract",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "TokenBlocklisted",
      },
    ],
    inheritedFunctions: {},
  },
  OptionFactory: {
    address: "0xb9e0c585296541d2c21a5a17d32727beb8650fea",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "MAX_FEE",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "UPGRADE_INTERFACE_VERSION",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "adjustFee",
        inputs: [
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "owner",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "blockToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "blocklist",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFees",
        inputs: [
          {
            name: "options",
            type: "address[]",
          },
          {
            name: "tokens",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimFees",
        inputs: [
          {
            name: "tokens",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createOption",
        inputs: [
          {
            name: "collateral",
            type: "address",
          },
          {
            name: "consideration",
            type: "address",
          },
          {
            name: "expirationDate",
            type: "uint40",
          },
          {
            name: "strike",
            type: "uint96",
          },
          {
            name: "isPut",
            type: "bool",
          },
        ],
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createOptions",
        inputs: [
          {
            name: "optionParams",
            type: "tuple[]",
            components: [
              {
                name: "collateral_",
                type: "address",
              },
              {
                name: "consideration_",
                type: "address",
              },
              {
                name: "expiration",
                type: "uint40",
              },
              {
                name: "strike",
                type: "uint96",
              },
              {
                name: "isPut",
                type: "bool",
              },
            ],
          },
        ],
        outputs: [
          {
            type: "address[]",
            name: "options",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "fee",
        outputs: [
          {
            type: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "initialize",
        inputs: [
          {
            name: "redemption_",
            type: "address",
          },
          {
            name: "option_",
            type: "address",
          },
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isApprovedForAll",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "operator",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isBlocked",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionClone",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "options",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionsClaimFees",
        inputs: [
          {
            name: "options",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "proxiableUUID",
        outputs: [
          {
            type: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redemptionClone",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setApprovalForAll",
        inputs: [
          {
            name: "operator",
            type: "address",
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint160",
          },
          {
            name: "token",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
            name: "success",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unblockToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "upgradeToAndCall",
        inputs: [
          {
            name: "newImplementation",
            type: "address",
          },
          {
            name: "data",
            type: "bytes",
          },
        ],
        stateMutability: "payable",
      },
      {
        type: "event",
        name: "ApprovalForAll",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: true,
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "FeeUpdated",
        inputs: [
          {
            name: "oldFee",
            type: "uint64",
          },
          {
            name: "newFee",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "OptionCreated",
        inputs: [
          {
            name: "collateral",
            type: "address",
            indexed: true,
          },
          {
            name: "consideration",
            type: "address",
            indexed: true,
          },
          {
            name: "expirationDate",
            type: "uint40",
          },
          {
            name: "strike",
            type: "uint96",
          },
          {
            name: "isPut",
            type: "bool",
          },
          {
            name: "option",
            type: "address",
            indexed: true,
          },
          {
            name: "redemption",
            type: "address",
          },
        ],
      },
      {
        type: "event",
        name: "TemplateUpdated",
      },
      {
        type: "event",
        name: "TokenBlocked",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "blocked",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "Upgraded",
        inputs: [
          {
            name: "implementation",
            type: "address",
            indexed: true,
          },
        ],
      },
      {
        type: "error",
        name: "AddressEmptyCode",
        inputs: [
          {
            name: "target",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "BlocklistedToken",
      },
      {
        type: "error",
        name: "ERC1967InvalidImplementation",
        inputs: [
          {
            name: "implementation",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ERC1967NonPayable",
      },
      {
        type: "error",
        name: "FailedCall",
      },
      {
        type: "error",
        name: "FailedDeployment",
      },
      {
        type: "error",
        name: "InsufficientBalance",
        inputs: [
          {
            name: "balance",
            type: "uint256",
          },
          {
            name: "needed",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidTokens",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "UUPSUnauthorizedCallContext",
      },
      {
        type: "error",
        name: "UUPSUnsupportedProxiableUUID",
        inputs: [
          {
            name: "slot",
            type: "bytes32",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  OpHook: {
    address: "0x7cbe32d4515f3dad77c82a1d60b8485936eb88a8",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "_poolManager",
            type: "address",
          },
          {
            name: "permit2",
            type: "address",
          },
        ],
      },
      {
        type: "function",
        name: "PERMIT2",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "addCash",
        inputs: [
          {
            name: "_cash",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "afterAddLiquidity",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "params",
            type: "tuple",
            components: [
              {
                name: "tickLower",
                type: "int24",
              },
              {
                name: "tickUpper",
                type: "int24",
              },
              {
                name: "liquidityDelta",
                type: "int256",
              },
              {
                name: "salt",
                type: "bytes32",
              },
            ],
          },
          {
            name: "delta0",
            type: "int256",
          },
          {
            name: "delta1",
            type: "int256",
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
          {
            type: "int256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "afterDonate",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "amount0",
            type: "uint256",
          },
          {
            name: "amount1",
            type: "uint256",
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "afterInitialize",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "sqrtPriceX96",
            type: "uint160",
          },
          {
            name: "tick",
            type: "int24",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "afterRemoveLiquidity",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "params",
            type: "tuple",
            components: [
              {
                name: "tickLower",
                type: "int24",
              },
              {
                name: "tickUpper",
                type: "int24",
              },
              {
                name: "liquidityDelta",
                type: "int256",
              },
              {
                name: "salt",
                type: "bytes32",
              },
            ],
          },
          {
            name: "delta0",
            type: "int256",
          },
          {
            name: "delta1",
            type: "int256",
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
          {
            type: "int256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "afterSwap",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "params",
            type: "tuple",
            components: [
              {
                name: "zeroForOne",
                type: "bool",
              },
              {
                name: "amountSpecified",
                type: "int256",
              },
              {
                name: "sqrtPriceLimitX96",
                type: "uint160",
              },
            ],
          },
          {
            name: "delta",
            type: "int256",
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
          {
            type: "int128",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allPools",
        inputs: [
          {
            name: "",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "address",
            name: "collateral",
          },
          {
            type: "address",
            name: "pricePool",
          },
          {
            type: "bool",
            name: "collateralIsOne",
          },
          {
            type: "address",
            name: "optionToken",
          },
          {
            type: "address",
            name: "cashToken",
          },
          {
            type: "bool",
            name: "optionIsOne",
          },
          {
            type: "uint24",
            name: "fee",
          },
          {
            type: "int24",
            name: "tickSpacing",
          },
          {
            type: "uint160",
            name: "sqrtPriceX96",
          },
          {
            type: "uint256",
            name: "expiration",
          },
          {
            type: "uint256",
            name: "strike",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "availableCollateral",
        inputs: [
          {
            name: "collateral",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "beforeAddLiquidity",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "params",
            type: "tuple",
            components: [
              {
                name: "tickLower",
                type: "int24",
              },
              {
                name: "tickUpper",
                type: "int24",
              },
              {
                name: "liquidityDelta",
                type: "int256",
              },
              {
                name: "salt",
                type: "bytes32",
              },
            ],
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "beforeDonate",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "amount0",
            type: "uint256",
          },
          {
            name: "amount1",
            type: "uint256",
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "beforeInitialize",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "sqrtPriceX96",
            type: "uint160",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "beforeRemoveLiquidity",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "params",
            type: "tuple",
            components: [
              {
                name: "tickLower",
                type: "int24",
              },
              {
                name: "tickUpper",
                type: "int24",
              },
              {
                name: "liquidityDelta",
                type: "int256",
              },
              {
                name: "salt",
                type: "bytes32",
              },
            ],
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "beforeSwap",
        inputs: [
          {
            name: "sender",
            type: "address",
          },
          {
            name: "key",
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
          {
            name: "params",
            type: "tuple",
            components: [
              {
                name: "zeroForOne",
                type: "bool",
              },
              {
                name: "amountSpecified",
                type: "int256",
              },
              {
                name: "sqrtPriceLimitX96",
                type: "uint160",
              },
            ],
          },
          {
            name: "hookData",
            type: "bytes",
          },
        ],
        outputs: [
          {
            type: "bytes4",
          },
          {
            type: "int256",
          },
          {
            type: "uint24",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "calculateCash",
        inputs: [
          {
            name: "optionAmount",
            type: "uint256",
          },
          {
            name: "price",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "calculateOption",
        inputs: [
          {
            name: "cashAmount",
            type: "uint256",
          },
          {
            name: "price",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "cash",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralBalance",
        inputs: [
          {
            name: "collateral",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralPools",
        inputs: [
          {
            name: "",
            type: "address",
          },
          {
            name: "",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "address",
            name: "collateral",
          },
          {
            type: "address",
            name: "pricePool",
          },
          {
            type: "bool",
            name: "collateralIsOne",
          },
          {
            type: "address",
            name: "optionToken",
          },
          {
            type: "address",
            name: "cashToken",
          },
          {
            type: "bool",
            name: "optionIsOne",
          },
          {
            type: "uint24",
            name: "fee",
          },
          {
            type: "int24",
            name: "tickSpacing",
          },
          {
            type: "uint160",
            name: "sqrtPriceX96",
          },
          {
            type: "uint256",
            name: "expiration",
          },
          {
            type: "uint256",
            name: "strike",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralPricePool",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getCollateralPrice",
        inputs: [
          {
            name: "collateral",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
            name: "price",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getHookPermissions",
        outputs: [
          {
            type: "tuple",
            name: "permissions",
            components: [
              {
                name: "beforeInitialize",
                type: "bool",
              },
              {
                name: "afterInitialize",
                type: "bool",
              },
              {
                name: "beforeAddLiquidity",
                type: "bool",
              },
              {
                name: "afterAddLiquidity",
                type: "bool",
              },
              {
                name: "beforeRemoveLiquidity",
                type: "bool",
              },
              {
                name: "afterRemoveLiquidity",
                type: "bool",
              },
              {
                name: "beforeSwap",
                type: "bool",
              },
              {
                name: "afterSwap",
                type: "bool",
              },
              {
                name: "beforeDonate",
                type: "bool",
              },
              {
                name: "afterDonate",
                type: "bool",
              },
              {
                name: "beforeSwapReturnDelta",
                type: "bool",
              },
              {
                name: "afterSwapReturnDelta",
                type: "bool",
              },
              {
                name: "afterAddLiquidityReturnDelta",
                type: "bool",
              },
              {
                name: "afterRemoveLiquidityReturnDelta",
                type: "bool",
              },
            ],
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "getPrice",
        inputs: [
          {
            name: "collateralPrice",
            type: "uint256",
          },
          {
            name: "option_",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPrice",
        inputs: [
          {
            name: "option_",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "getPriceX64",
        inputs: [
          {
            name: "sqrtPriceX96",
            type: "uint160",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "pure",
      },
      {
        type: "function",
        name: "getPrices",
        inputs: [
          {
            name: "collateral",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "tuple[]",
            name: "prices",
            components: [
              {
                name: "collateral",
                type: "address",
              },
              {
                name: "optionToken",
                type: "address",
              },
              {
                name: "price",
                type: "uint256",
              },
              {
                name: "collateralPrice",
                type: "uint256",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "initPool",
        inputs: [
          {
            name: "optionToken",
            type: "address",
          },
          {
            name: "cashToken",
            type: "address",
          },
          {
            name: "collateral",
            type: "address",
          },
          {
            name: "pricePool",
            type: "address",
          },
          {
            name: "fee",
            type: "uint24",
          },
        ],
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "currency0",
                type: "address",
              },
              {
                name: "currency1",
                type: "address",
              },
              {
                name: "fee",
                type: "uint24",
              },
              {
                name: "tickSpacing",
                type: "int24",
              },
              {
                name: "hooks",
                type: "address",
              },
            ],
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "optionCashPool",
        inputs: [
          {
            name: "",
            type: "address",
          },
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "address",
            name: "collateral",
          },
          {
            type: "address",
            name: "pricePool",
          },
          {
            type: "bool",
            name: "collateralIsOne",
          },
          {
            type: "address",
            name: "optionToken",
          },
          {
            type: "address",
            name: "cashToken",
          },
          {
            type: "bool",
            name: "optionIsOne",
          },
          {
            type: "uint24",
            name: "fee",
          },
          {
            type: "int24",
            name: "tickSpacing",
          },
          {
            type: "uint160",
            name: "sqrtPriceX96",
          },
          {
            type: "uint256",
            name: "expiration",
          },
          {
            type: "uint256",
            name: "strike",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionPoolList",
        inputs: [
          {
            name: "",
            type: "address",
          },
          {
            name: "",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "address",
            name: "collateral",
          },
          {
            type: "address",
            name: "pricePool",
          },
          {
            type: "bool",
            name: "collateralIsOne",
          },
          {
            type: "address",
            name: "optionToken",
          },
          {
            type: "address",
            name: "cashToken",
          },
          {
            type: "bool",
            name: "optionIsOne",
          },
          {
            type: "uint24",
            name: "fee",
          },
          {
            type: "int24",
            name: "tickSpacing",
          },
          {
            type: "uint160",
            name: "sqrtPriceX96",
          },
          {
            type: "uint256",
            name: "expiration",
          },
          {
            type: "uint256",
            name: "strike",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionPools",
        inputs: [
          {
            name: "",
            type: "bytes32",
          },
        ],
        outputs: [
          {
            type: "address",
            name: "collateral",
          },
          {
            type: "address",
            name: "pricePool",
          },
          {
            type: "bool",
            name: "collateralIsOne",
          },
          {
            type: "address",
            name: "optionToken",
          },
          {
            type: "address",
            name: "cashToken",
          },
          {
            type: "bool",
            name: "optionIsOne",
          },
          {
            type: "uint24",
            name: "fee",
          },
          {
            type: "int24",
            name: "tickSpacing",
          },
          {
            type: "uint160",
            name: "sqrtPriceX96",
          },
          {
            type: "uint256",
            name: "expiration",
          },
          {
            type: "uint256",
            name: "strike",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionPrice",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "paused",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "pm",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "poolManager",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setOptionPrice",
        inputs: [
          {
            name: "optionPrice_",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "swapForOption",
        inputs: [
          {
            name: "optionToken",
            type: "address",
          },
          {
            name: "cashToken",
            type: "address",
          },
          {
            name: "amount",
            type: "int256",
          },
          {
            name: "to",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "swapForOption",
        inputs: [
          {
            name: "optionToken",
            type: "address",
          },
          {
            name: "cashToken",
            type: "address",
          },
          {
            name: "cashAmount",
            type: "int256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "validOptions",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "event",
        name: "EmergencyWithdraw",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "FeeCollected",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "FeeRateUpdated",
        inputs: [
          {
            name: "oldRate",
            type: "uint256",
          },
          {
            name: "newRate",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "FeeRecipientUpdated",
        inputs: [
          {
            name: "oldRecipient",
            type: "address",
            indexed: true,
          },
          {
            name: "newRecipient",
            type: "address",
            indexed: true,
          },
        ],
      },
      {
        type: "event",
        name: "OptionPoolUpdated",
        inputs: [
          {
            name: "oldPool",
            type: "address",
            indexed: true,
          },
          {
            name: "newPool",
            type: "address",
            indexed: true,
          },
        ],
      },
      {
        type: "event",
        name: "Paused",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
      },
      {
        type: "event",
        name: "Swap",
        inputs: [
          {
            name: "",
            type: "address",
          },
          {
            name: "",
            type: "address",
          },
          {
            name: "",
            type: "int256",
          },
          {
            name: "",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Unpaused",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "EnforcedPause",
      },
      {
        type: "error",
        name: "ExpectedPause",
      },
      {
        type: "error",
        name: "HookNotImplemented",
      },
      {
        type: "error",
        name: "InvalidPool",
      },
      {
        type: "error",
        name: "NotPoolManager",
      },
      {
        type: "error",
        name: "NotSelf",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
} as const;

export default baseContracts;
