/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
const mainnetContracts = {
  chainId: 1,
  deploymentBlock: 24116718,
  StableToken: {
    address: "0x3cd07baddc0d9a0506c412095a05394e990a252b",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  ShakyToken: {
    address: "0x0b91e9fc51e75b7053d1a509e3bc1ed0dba25a9a",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "burn",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
  Redemption: {
    address: "0x95d978ffeaed538e4aab387bc04724b8ed6c5cac",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "consideration_",
            type: "address",
          },
          {
            name: "expirationDate_",
            type: "uint256",
          },
          {
            name: "strike_",
            type: "uint256",
          },
          {
            name: "isPut_",
            type: "bool",
          },
        ],
      },
      {
        type: "function",
        name: "STRIKE_DECIMALS",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "_factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "_redeemPair",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "adjustFee",
        inputs: [
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFees",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "collDecimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateral",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "collateralData",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "address_",
                type: "address",
              },
              {
                name: "name",
                type: "string",
              },
              {
                name: "symbol",
                type: "string",
              },
              {
                name: "decimals",
                type: "uint8",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consDecimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consideration",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "considerationData",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "address_",
                type: "address",
              },
              {
                name: "name",
                type: "string",
              },
              {
                name: "symbol",
                type: "string",
              },
              {
                name: "decimals",
                type: "uint8",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
          {
            name: "caller",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "expirationDate",
        outputs: [
          {
            type: "uint40",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fee",
        outputs: [
          {
            type: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fees",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "init",
        inputs: [
          {
            name: "collateral_",
            type: "address",
          },
          {
            name: "consideration_",
            type: "address",
          },
          {
            name: "expirationDate_",
            type: "uint40",
          },
          {
            name: "strike_",
            type: "uint256",
          },
          {
            name: "isPut_",
            type: "bool",
          },
          {
            name: "option_",
            type: "address",
          },
          {
            name: "factory_",
            type: "address",
          },
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isPut",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lock",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "locked",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "option",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeemConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeemConsideration",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "strike",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "sweep",
        inputs: [
          {
            name: "holder",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "sweep",
        inputs: [
          {
            name: "holders",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toCollateral",
        inputs: [
          {
            name: "consAmount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "toConsideration",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unlock",
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "ContractLocked",
      },
      {
        type: "event",
        name: "ContractUnlocked",
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Redeemed",
        inputs: [
          {
            name: "option",
            type: "address",
          },
          {
            name: "token",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ArithmeticOverflow",
      },
      {
        type: "error",
        name: "ContractExpired",
      },
      {
        type: "error",
        name: "ContractNotExpired",
      },
      {
        type: "error",
        name: "FeeOnTransferNotSupported",
      },
      {
        type: "error",
        name: "InsufficientBalance",
      },
      {
        type: "error",
        name: "InsufficientCollateral",
      },
      {
        type: "error",
        name: "InsufficientConsideration",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidValue",
      },
      {
        type: "error",
        name: "LockedContract",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "TokenBlocklisted",
      },
    ],
    inheritedFunctions: {},
  },
  Option: {
    address: "0x19041ba000a71b325cfb0f62e455f841610c1106",
    abi: [
      {
        type: "constructor",
        inputs: [
          {
            name: "name_",
            type: "string",
          },
          {
            name: "symbol_",
            type: "string",
          },
          {
            name: "redemption__",
            type: "address",
          },
        ],
      },
      {
        type: "function",
        name: "adjustFee",
        inputs: [
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "spender",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "spender",
            type: "address",
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "balanceOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "balancesOf",
        inputs: [
          {
            name: "account",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "collateral",
                type: "uint256",
              },
              {
                name: "consideration",
                type: "uint256",
              },
              {
                name: "option",
                type: "uint256",
              },
              {
                name: "redemption",
                type: "uint256",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFees",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "collateral",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "consideration",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "decimals",
        outputs: [
          {
            type: "uint8",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "details",
        outputs: [
          {
            type: "tuple",
            components: [
              {
                name: "option",
                type: "address",
              },
              {
                name: "redemption",
                type: "address",
              },
              {
                name: "collateral",
                type: "tuple",
                components: [
                  {
                    name: "address_",
                    type: "address",
                  },
                  {
                    name: "name",
                    type: "string",
                  },
                  {
                    name: "symbol",
                    type: "string",
                  },
                  {
                    name: "decimals",
                    type: "uint8",
                  },
                ],
              },
              {
                name: "consideration",
                type: "tuple",
                components: [
                  {
                    name: "address_",
                    type: "address",
                  },
                  {
                    name: "name",
                    type: "string",
                  },
                  {
                    name: "symbol",
                    type: "string",
                  },
                  {
                    name: "decimals",
                    type: "uint8",
                  },
                ],
              },
              {
                name: "expiration",
                type: "uint256",
              },
              {
                name: "strike",
                type: "uint256",
              },
              {
                name: "isPut",
                type: "bool",
              },
            ],
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "exercise",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "expirationDate",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "factory",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "fee",
        outputs: [
          {
            type: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "init",
        inputs: [
          {
            name: "redemption_",
            type: "address",
          },
          {
            name: "owner",
            type: "address",
          },
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isPut",
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "lock",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "mint",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "name",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "account",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redeem",
        inputs: [
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "redemption",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "strike",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "symbol",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "totalSupply",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "transfer",
        inputs: [
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
            name: "success",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        outputs: [
          {
            type: "bool",
            name: "success",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unlock",
        stateMutability: "nonpayable",
      },
      {
        type: "event",
        name: "Approval",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "spender",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "ContractLocked",
      },
      {
        type: "event",
        name: "ContractUnlocked",
      },
      {
        type: "event",
        name: "Exercise",
        inputs: [
          {
            name: "longOption",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Mint",
        inputs: [
          {
            name: "longOption",
            type: "address",
          },
          {
            name: "holder",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
      },
      {
        type: "event",
        name: "Transfer",
        inputs: [
          {
            name: "from",
            type: "address",
            indexed: true,
          },
          {
            name: "to",
            type: "address",
            indexed: true,
          },
          {
            name: "value",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "ArithmeticOverflow",
      },
      {
        type: "error",
        name: "ContractExpired",
      },
      {
        type: "error",
        name: "ContractNotExpired",
      },
      {
        type: "error",
        name: "FeeOnTransferNotSupported",
      },
      {
        type: "error",
        name: "InsufficientBalance",
      },
      {
        type: "error",
        name: "InsufficientCollateral",
      },
      {
        type: "error",
        name: "InsufficientConsideration",
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidValue",
      },
      {
        type: "error",
        name: "LockedContract",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "TokenBlocklisted",
      },
    ],
    inheritedFunctions: {},
  },
  OptionFactory: {
    address: "0xc9071dff211985709be04ba7fb0abcba82e609dc",
    abi: [
      {
        type: "constructor",
      },
      {
        type: "function",
        name: "MAX_FEE",
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "UPGRADE_INTERFACE_VERSION",
        outputs: [
          {
            type: "string",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "adjustFee",
        inputs: [
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "allowance",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "owner",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "uint256",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "approve",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "amount",
            type: "uint256",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "blockToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "blocklist",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "claimFees",
        inputs: [
          {
            name: "options",
            type: "address[]",
          },
          {
            name: "tokens",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "claimFees",
        inputs: [
          {
            name: "tokens",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createOption",
        inputs: [
          {
            name: "collateral",
            type: "address",
          },
          {
            name: "consideration",
            type: "address",
          },
          {
            name: "expirationDate",
            type: "uint40",
          },
          {
            name: "strike",
            type: "uint96",
          },
          {
            name: "isPut",
            type: "bool",
          },
        ],
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "createOptions",
        inputs: [
          {
            name: "optionParams",
            type: "tuple[]",
            components: [
              {
                name: "collateral_",
                type: "address",
              },
              {
                name: "consideration_",
                type: "address",
              },
              {
                name: "expiration",
                type: "uint40",
              },
              {
                name: "strike",
                type: "uint96",
              },
              {
                name: "isPut",
                type: "bool",
              },
            ],
          },
        ],
        outputs: [
          {
            type: "address[]",
            name: "options",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "fee",
        outputs: [
          {
            type: "uint64",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "initialize",
        inputs: [
          {
            name: "redemption_",
            type: "address",
          },
          {
            name: "option_",
            type: "address",
          },
          {
            name: "fee_",
            type: "uint64",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "isApprovedForAll",
        inputs: [
          {
            name: "owner",
            type: "address",
          },
          {
            name: "operator",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "isBlocked",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionClone",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "options",
        inputs: [
          {
            name: "",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "optionsClaimFees",
        inputs: [
          {
            name: "options",
            type: "address[]",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "owner",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "proxiableUUID",
        outputs: [
          {
            type: "bytes32",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "redemptionClone",
        outputs: [
          {
            type: "address",
          },
        ],
        stateMutability: "view",
      },
      {
        type: "function",
        name: "renounceOwnership",
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "setApprovalForAll",
        inputs: [
          {
            name: "operator",
            type: "address",
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferFrom",
        inputs: [
          {
            name: "from",
            type: "address",
          },
          {
            name: "to",
            type: "address",
          },
          {
            name: "amount",
            type: "uint160",
          },
          {
            name: "token",
            type: "address",
          },
        ],
        outputs: [
          {
            type: "bool",
            name: "success",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "transferOwnership",
        inputs: [
          {
            name: "newOwner",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "unblockToken",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
        stateMutability: "nonpayable",
      },
      {
        type: "function",
        name: "upgradeToAndCall",
        inputs: [
          {
            name: "newImplementation",
            type: "address",
          },
          {
            name: "data",
            type: "bytes",
          },
        ],
        stateMutability: "payable",
      },
      {
        type: "event",
        name: "ApprovalForAll",
        inputs: [
          {
            name: "owner",
            type: "address",
            indexed: true,
          },
          {
            name: "operator",
            type: "address",
            indexed: true,
          },
          {
            name: "approved",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "FeeUpdated",
        inputs: [
          {
            name: "oldFee",
            type: "uint64",
          },
          {
            name: "newFee",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "Initialized",
        inputs: [
          {
            name: "version",
            type: "uint64",
          },
        ],
      },
      {
        type: "event",
        name: "OptionCreated",
        inputs: [
          {
            name: "collateral",
            type: "address",
            indexed: true,
          },
          {
            name: "consideration",
            type: "address",
            indexed: true,
          },
          {
            name: "expirationDate",
            type: "uint40",
          },
          {
            name: "strike",
            type: "uint96",
          },
          {
            name: "isPut",
            type: "bool",
          },
          {
            name: "option",
            type: "address",
            indexed: true,
          },
          {
            name: "redemption",
            type: "address",
          },
        ],
      },
      {
        type: "event",
        name: "TemplateUpdated",
      },
      {
        type: "event",
        name: "TokenBlocked",
        inputs: [
          {
            name: "token",
            type: "address",
          },
          {
            name: "blocked",
            type: "bool",
          },
        ],
      },
      {
        type: "event",
        name: "Upgraded",
        inputs: [
          {
            name: "implementation",
            type: "address",
            indexed: true,
          },
        ],
      },
      {
        type: "error",
        name: "AddressEmptyCode",
        inputs: [
          {
            name: "target",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "BlocklistedToken",
      },
      {
        type: "error",
        name: "ERC1967InvalidImplementation",
        inputs: [
          {
            name: "implementation",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "ERC1967NonPayable",
      },
      {
        type: "error",
        name: "FailedCall",
      },
      {
        type: "error",
        name: "FailedDeployment",
      },
      {
        type: "error",
        name: "InsufficientBalance",
        inputs: [
          {
            name: "balance",
            type: "uint256",
          },
          {
            name: "needed",
            type: "uint256",
          },
        ],
      },
      {
        type: "error",
        name: "InvalidAddress",
      },
      {
        type: "error",
        name: "InvalidInitialization",
      },
      {
        type: "error",
        name: "InvalidTokens",
      },
      {
        type: "error",
        name: "NotInitializing",
      },
      {
        type: "error",
        name: "ReentrancyGuardReentrantCall",
      },
      {
        type: "error",
        name: "SafeERC20FailedOperation",
        inputs: [
          {
            name: "token",
            type: "address",
          },
        ],
      },
      {
        type: "error",
        name: "UUPSUnauthorizedCallContext",
      },
      {
        type: "error",
        name: "UUPSUnsupportedProxiableUUID",
        inputs: [
          {
            name: "slot",
            type: "bytes32",
          },
        ],
      },
    ],
    inheritedFunctions: {},
  },
} as const;

export default mainnetContracts;
